### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by juhi1296** [morungos/wordnet#24]
var word = new WordNet('/home/juhi/WordNet-3.0');
               ^

ReferenceError: WordNet is not defined
    at Object.<anonymous> (/home/juhi/sense2.js:3:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

**Comment by juhi1296** [comment]
Please help in solving this error .
I have already installed node-wordnet and wndb-with-exceptions and wordnet-db.
Still getting this error.

**Comment by morungos** [comment]
Could you maybe send a more complete script? I'm guessing there is a require statement before this, setting up the value for `WordNet`

**Comment by morungos** [comment]
If that's not there (it should probably be better documented, my bad) you probably want to add a line:

    var WordNet = require('node-wordnet');

Before you call `new WordNet`

**Comment by morungos** [comment]
Did that help?

**Comment by isaklafleur** [comment]
@juhi1296 

Try this:

```
const path = require("path");
const WordNet = require("node-wordnet");
const wordNetFiles = path.join(__dirname, "../../data/wordNet/");
const wordnet = new WordNet(wordNetFiles);

wordnet.lookup("client", function(results) {
  results.forEach(function(result) {
    console.log("------------------------------------");
    console.log(result.synsetOffset);
    console.log(result.pos);
    console.log(result.lemma);
    console.log(result.synonyms);
    console.log(result.pos);
    console.log(result.gloss);
  });
});

```

**Comment by angelokal** [comment]
`<script>

       var WordNet = require('node-wordnet');
        var wordnet= new WordNet();

        wordnet.lookup('node', function(results) {
            results.forEach(function(result) {
                console.log('------------------------------------');
                console.log(result.synsetOffset);
                console.log(result.pos);
                console.log(result.lemma);
                console.log(result.synonyms);
                console.log(result.pos);
                console.log(result.gloss);
            });
        });
    </script>`

help me pls, new "WordNet" and "require" error ReferenceError: require is not defined

**Comment by morungos** [comment]
If `require` isn't defined... maybe you're using this in a browser? It's intended a Node.js module because it needs access to some fairly large files (i.e., the WordNet database). 

What's your JavaScript environment?

**Comment by angelokal** [comment]
sorry, i'm a beginner in this field. I'm using phpstorm and i've created an html5 boilerplate project

**Comment by morungos** [comment]
Oh yes, the WordNet module is really intended to be used server-side. I've not even considered how it might work entirely in a browser, because the files are a bit huge. You'd probably be better with a PHP API for WordNet, such as: https://github.com/Josiah/WordNet. And you'd want to set up a server endpoint for the analysis so that front end requests are pushed through for analysis. The data can then be collected in the browser and used that way. 

I have used PHP a while back, but it probably wouldn't be my technology of choice for deeper language analysis. We now do most of our work using JavaScript and server-side systems such as Node.js. 

But it does depend on your usage. if you are only interested in some aspects of language, you might be able to pull out a segment of WordNet into JSON files and then you can make queries easy. I'd done this for sentiment analysis, for example, using WordNet Affect and WordNet Domains, which are fairly small compared to the whole of WordNet.

**Comment by angelokal** [comment]
io non devo usare il php, io dovrei sviluppare una piattaforma in cui l'utente effettua una ricerca. La ricerca però viene effettuata con wordnet e mi serve poi prendere i risultati e stamparli. non è sufficiente solo javascript e html?
ps. sorry for my english

**Comment by angelokal** [comment]
I do not have to use php, I should develop a platform where the user performs a search. But the search is done with wordnet and then I need to take the results and print them. is not enough javascript and html only?
ps. sorry for my english

**Comment by morungos** [comment]
It's *way* better than my Italian :-)

No, you'll need some server-side technology. PHP might be the easiest for you, if you're starting out in the field. And the code at: https://github.com/Josiah/WordNet might have some examples that'll get you started. 

If you are happy using Node.js, which will make the server-side very different, and affect the way you serve your site or application, then I can point you at some examples.

**Comment by angelokal** [comment]
this project is for an exam and I have no constraints on the technology so if you recommend me nodejs and you can help me, then I accept.

**Comment by angelokal** [comment]
sorry but now I have to go to work and I can not continue the conversation. I'll answer you as soon as I finish. thank you.

**Comment by angelokal** [comment]
then?
