### ISSUE TITLE
Synsets are numbered backwards!

### ISSUE THREAD

**Issue by R-seny** [morungos/wordnet#28]
I ran into a very unfortunate inconsistency in word sense numbering between the python WordNet interface (which agrees with to the word net web interface) and this package.

For example, querying the 4th sense of the word "go" (as a noun), by running wordnet.findSense("go#n#4", console.log) gives me 'a time for working (after which you will be relieved by someone else); "it\'s my go"; "a spell of work", which corresponds to "go.n.01" in python implementation, and also corresponds to the first line in the web-based wordnet interface [(see here)](http://wordnetweb.princeton.edu/perl/webwn?s=go&sub=Search+WordNet&o2=&o0=1&o8=1&o1=1&o7=&o5=&o9=&o6=&o3=&o4=&h=).

It is not just a coincidence: the numbering is reversed for all parts of speech. In the very least, it seems to be reversed consistently, but it's very desirable to make it consistent with the official numbering.

**Comment by morungos** [comment]
Noted. I've rewritten almost the whole of the lower layers, and this showed when I increased the testing. It used to use some weird recursive code to handle the asynchronous coding, and I've written it to use promises going forwards, so the reversal should fall out (that's what the tests suggest). The commit that contains all this is: 4750a9f6a. I'm closing for now, as this is implemented in develop, but well done for finding and reporting it.
