### ISSUE TITLE
validForms question

### ISSUE THREAD

**Issue by silentrob** [morungos/wordnet#5]
Sorry for cross posting this - I made a comment in Natural as well.

validForms("fought#v",cb) vs validForms("fought",cb) yield different results. 

[ 'fight#v' ] vs undefined

By looking at the second, it seems like we iterate though all POS and *should* return an array of all the valid forms, but that is not the case. Is that the intended behaviour or a bug?

**Comment by morungos** [comment]
That's certainly not the intended behaviour. Good catch. In all cases, specifying a POS should simply filter the results.

**Comment by morungos** [comment]
A quick check shows that this is one of the exceptions in `verb.exc`, so it's probably an interaction with the morphological exception handling.

**Comment by silentrob** [comment]
Amazing thank!
