### ISSUE TITLE
Add an optional LRU cache

### ISSUE THREAD

**Issue by morungos** [morungos/wordnet#7]
Suggestion (and a good one) by Rob Ellis.

**Comment by silentrob** [comment]
:+1:

**Comment by morungos** [comment]
So, a few thoughts: we really want this to be optional, and ideally someone can plug in their own cache should they want to. Also, it ought to handle all the useful endpoints, rather than just one or two. This means we need a clean way of encoding the queries at the front end of the API. Essentially this means that each and every API call needs to correspond to a stringified form that is easy to query, although obviously we only need to use this if there's a cache set. `lru-cache` seems a decent candidate (and I've used it before).

**Comment by silentrob** [comment]
I'm really not overly hung up on weather or not it should be optional or extendable (swappable), providing the solution is in-memory and maybe we have knob to tune how big the cache is.

But I do agree it should be should cover all the endpoints or the ones that would benefit the most from the cache.

**Comment by morungos** [comment]
Completed in 0e2ab90

**Comment by silentrob** [comment]
Amazing. I will play with this tomorrow - did you notice and speed improvements?
